### PR TITLE
Timber version requirement downgrade

### PR DESCRIPTION
**Pull request by sdunham**
The official release of Timber 2 is taking much longer than anticipated, and until that happens we consider the Timber 2 branch to be a bit unstable to rely on in production. Because of this, we're updating Greg to require Timber 1 instead of Timber 2. This PR makes the necessary updates to implement this change.

Once Timber 2 is officially released and stable, reverting these changes should be fairly simple.

### CODE REVIEW

**Review by akoziolsc — APPROVED** [review]
Code looks good. Scott will add a comment to readme file for people looking for Timber2  version of the plugin.

**Comment by acobster** [comment]
I have zero opinions about how to go about this but it's worth noting that Timber 2.x is [now in Beta](https://github.com/timber/timber/discussions/2625#discussioncomment-3358882). So it should be stable at least in the sense of no breaking changes.

**Comment by sdunham** [comment]
Yeah, my use of the word "unstable" was probably a bit harsh. We've just run into a handful of small issues with the few projects that currently rely on Timber 2. Because of that, we're trying to avoid releasing any new projects that rely on it until it's fully through the release process.

I'm planning to give the beta a spin soon to see if those issues have been addressed, and if not we can create issues where necessary. I'm hoping this 1.x version of Greg will be pretty short-lived!

**Comment by acobster** [comment]
Word. Thanks for taking care of Baby Greg.

**Pull request merged**
